### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by jmreidy** [orchestrate-io/orchestrate-java-client#67]
Am I totally missing it? 

And it looks like the main addition from 0.7 to 0.9 was event search, right?

**Comment by duvander** [comment]
That's correct. Documentation on this feature is forthcoming.

**Comment by housejester** [comment]
Just as an update, we added a RELEASE_NOTES.md in the latest pull requests. Thanks for suggesting.

**Comment by jmreidy** [comment]
Awesome. Thanks!
